namespace: stnvivanco92-dev

app:
  name: backend-api
  role: backend-api
  image: savivancofi/backend-api
  tag: v1
  replicas: 1
  containerPort: 8080
  servicePort: 8080
  createRoute: false

envFrom:
  - configMapRef:
      name: backend-api-config